### ISSUE TITLE
Flag to auto ignore `devDependencies`

### ISSUE THREAD

**Issue by TJkrusinski** [maxogden/atom-shell-packager#11]
First want to make sure this is sensible, but would a flag that ignores all listed `devDependencies` in the package.json to help with keeping the `--ignore` flag from being massive be useful? Can send PR if so.

**Comment by mafintosh** [comment]
This should already be supported if you add the `--prune` flag (https://github.com/maxogden/atom-shell-packager/blob/master/index.js#L94-L101)

**Comment by TJkrusinski** [comment]
Ah, perfect, thanks!
