### ISSUE TITLE
npm prune option

### ISSUE THREAD

**Issue by remixz** [maxogden/atom-shell-packager#4]
would be nice to have an option that runs `npm prune --production` on the app, then people could add this and `atom-shell` to dev deps, and it just removes them

**Comment by maxogden** [comment]
great idea, it could even run it after it copied the app into the App folder so its non-destructive to the source folder

it might be worth using https://github.com/datproject/gasket for automating the multi-process step stuff if this gets more complex, e.g. https://github.com/meandavejustice/gh-pages-deploy/blob/master/index.js
